AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Hello Inx Ocean
Transform:
- AWS::Serverless-2016-10-31

Resources:
  loggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/logger.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /inx/log
            Method: get

  addFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/add.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /inx/add
            Method: post

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"

